################################################################################
# R Script Header
# 
# Created by: Felipe Sanchez
# Contact: anfesanz@gmail.com
# Date: July 2023
#
# Description: This script processes data from the "report.xlsx" file generated by CEPAL/CELADE Redatam+SP on June 20, 2023. The steps are as follows:
# 1. Data cleaning is performed using a portion of the code found in "Data Clean.R"
# 2. It is assumed that individuals do not change their educational level after the age of 40. Therefore, information is extracted for those aged between 40-44 and 80-84 years (as the final open age group is 85+), and educational weights are calculated for each age group.
# 3. A portion of the code "opentoclose.R" is invoked that works with the weighted information. It calculates pi1, pi2, and pi3 (this is the cumulative educational distribution equation 3 in Speringer, 2019), computes the logit of each pi, and extrapolates these values to estimate the closed groups after 80-84, namely 85-89, and so on. The extrapolated data are then used to calculate pi (using the logistic function which is the inverse of the logit), and these pi values are used to compute the weights. This part of the code can be expanded to extrapolate any required number of groups.
# One aproach to calculate the survival ratio is use two censuses (see Lutz 2007 p210) but as Colombia has an interval of 13 years between the last two censuses as the majority of the countries in Latin America. The survival ratio for the 13 years is no appropiate for the backward estimation each 5 years (at least that there assuming linearity in the growth or decrease that is one case explored with the debugg of the census)
#Other option is estimate this from the national household surveys (see Lutz 2007 p210).
# Input: "report.xlsx"
#
# Outputs:
# - From the first step, an object called "Census2018_d" (df) that contains the cleaned (debugged) data.
# - From the second step, an object called "Census2018_w" (df_w) that contains the educational percentage weights for each age group (sum of weights by age equals 1).
# - From the third step, an object called "Census2018_we "df_est" that contains the educational weights for each age group, including estimated values for closed intervals.
################################################################################

# Clear the workspace
rm(list = ls(all = TRUE))  

# Set the working directory
getwd()
setwd("/Users/felipesanchez/Documents/GitHub/PopEdu Reconstruction/")

# Load libraries
library(tidyverse)
library(readxl)

# Load user-defined functions
source("Code/functions.R")
#############################################################################


#Read the data
#############################################################################
# Define the local file path for downloading the Excel file
local_file <- "Data Original/reporte2018.xlsx"
# Read the downloaded Excel file into R
data <- read_excel("Data Original/reporte2018.xlsx", skip = 12)

#Clean the data by education level to df
########################################
source("Code/1.Census2018Debug.R")
# Print the resulting data
print(df)

#Setting values to estimate the last close interval
###################################################
# Age to start extracting records
age_start_reg <- 40
# Extract the last age group and remove the "+" sign if it exists
age_last <- as.numeric(stringr::str_replace(df$age_group[nrow(df)], "\\+$", ""))
# Find the index where the age_group starts with 40
#startregister <- which(str_detect(df$age_group, paste("^", age_start_reg, "-", sep = "")))

#Extract the information starting from 15 years and calculate the weights by age group
df_w <- df %>%
  filter(str_detect(age_group, "^(1[5-9]|[2-9][0-9])")) %>% # Excluding ages bellow 15
  rowwise() %>%
  mutate(across(starts_with("edu"), ~ ./sum(c_across(starts_with("edu")))))


#If in 2005 i have 80 people at the age of 85 and in 2018 I have 60 calculate the growth by year


#Estimate the last close interval 
#################################
source("Code/2.CensusbyEduOpentoClose.R")
# Print the resulting data
print(df_est)

#Rename
Census2018_d <- df
Census2018_w <- df_w
Census2018_we <- df_est


Census2018 <- tibble(
  id = c("Census2018_d", "Census2018_w", "Census2018_we"),
  data = list(Census2018_d, Census2018_w, Census2018_we)
)


#Save information
saveRDS(Census2018, "Data Created/Census2018.rds")




