################################################################################
# R Script Header
# 
# Created by: Felipe Sanchez
# Contact: anfesanz@gmail.com
# Date: July 2023
#
# Description: This script processes data from the "report.xlsx" file generated by CEPAL/CELADE Redatam+SP on June 20, 2023. The steps are as follows:
# 1. Data retrieval: Extract age and sex data from the following website:
#    - Source: https://www.dane.gov.co/index.php/estadisticas-por-tema/demografia-y-poblacion/proyecciones-de-poblacion
#    - Data file: https://www.dane.gov.co/files/censo2018/proyecciones-de-poblacion/Nacional/DCD-area-sexo-edad-proypoblacion-Nac-1950-2019.xlsx
# 2. Data cleaning: Reclassify ages into age groups. Keep data for the years 1950, 1960, 1970, 1980, 1990, 2000, 2010, and 2018 for comparison and graphing of differences by sex.
#
# Input:
# - "DCD-area-sexo-edad-proypoblacion-Nac-1950-2019.xlsx"
#
# Output:
# - Graph with population by sex in 2018 and the compison with back years in "Output/danereconstruction.png"
################################################################################



# Clear the workspace
rm(list = ls(all = TRUE))  

# Set the working directory
getwd()
setwd("/Users/felipesanchez/Documents/UoM/PhD/Phd Second Year/PopEdu Reconstruction/")

# Load libraries
library(tidyverse)
library(viridis)
library(readxl)
#############################################################################

# Specify the URL of the Excel file
excel_url <- "https://www.dane.gov.co/files/censo2018/proyecciones-de-poblacion/Nacional/DCD-area-sexo-edad-proypoblacion-Nac-1950-2019.xlsx"

# Define the local file path for downloading the Excel file
local_file <- "Data Original/DCD-area-sexo-edad-proypoblacion-Nac-1950-2019.xlsx"

# Download the Excel file from the DANE website
download.file(url = excel_url, destfile = local_file, mode = "wb")

# Read the downloaded Excel file into R
data <- read_excel(local_file, skip = 11)


df2 <- data %>%
  rename(year = "AÑO", area="ÁREA GEOGRÁFICA") %>%
  filter(area == "Total") %>%
  select(-DP, -DPNOM, -starts_with("Total"), -area) %>%
  pivot_longer(cols = !year,, names_to = "sexage", values_to = "pop") %>% # Convert columns into rows
  separate(sexage, into = c("sex", "age"), sep = "_", remove = FALSE) %>%
  select(-sexage) %>%
  mutate(sex = if_else(sex == "Hombres", "1", sex), sex = if_else(sex == "Mujeres", "2", sex),age=as.numeric(age)) %>%
  # Create categories
  mutate(age_group = case_when(
    age <= 4 ~ "0-4",
    age >= 5 & age <= 9 ~ "5-9",
    age >= 10 & age <= 14 ~ "10-14",
    age >= 15 & age <= 19 ~ "15-19",
    age >= 20 & age <= 24 ~ "20-24",
    age >= 25 & age <= 29 ~ "25-29",
    age >= 30 & age <= 34 ~ "30-34",
    age >= 35 & age <= 39 ~ "35-39",
    age >= 40 & age <= 44 ~ "40-44",
    age >= 45 & age <= 49 ~ "45-49",
    age >= 50 & age <= 54 ~ "50-54",
    age >= 55 & age <= 59 ~ "55-59",
    age >= 60 & age <= 64 ~ "60-64",
    age >= 65 & age <= 69 ~ "65-69",
    age >= 70 & age <= 74 ~ "70-74",
    age >= 75 & age <= 79 ~ "75-79",
    age >= 80 & age <= 84 ~ "80-84",
    age >= 85 ~ "85+"),
    # Convert to factor
  age_group = factor(age_group,level = c("0-4", "5-9", "10-14", "15-19", "20-24", "25-29",
                                         "30-34", "35-39", "40-44", "45-49", "50-54", "55-59",
                                         "60-64", "65-69", "70-74", "75-79", "80-84", "85+")
                     )
  ) %>%
  group_by(year, sex, age_group) %>%
  summarize(pop = sum(pop)) %>%
  separate(age_group, into = c("age", "group"), sep = c("-"), remove = FALSE)%>%
  select(-group)%>%
  mutate(age = str_replace(age, fixed("+"), "")) %>%
  mutate(age=as.numeric(age))

#stack data for ggplot, filter World population and required years
df2 <- df2 %>%
  mutate(pop = pop/1e03, country = "Colombia") %>%
  filter(year %in% c(1950, 1960, 1970, 1980, 1990, 2000, 2010, 2018))
#add extra rows and numeric age variable for geom_step used for 2100
df2 <- df2 %>% 
  mutate(ageno = as.numeric(age) - 0.5)
df2 <- df2 %>%
  bind_rows(df2 %>% filter(year==2018, age=="85+") %>% mutate(ageno = ageno + 1)) 


danereconstruction<-ggplot(data = df2, aes(x = age, y = pop, fill = year)) +
  #bars for all but 2018
  geom_bar(data = df2 %>% filter(sex == "2", year != 2018) %>% arrange(rev(year)),
           stat = "identity",
           position = "identity") +
  geom_bar(data = df2 %>% filter(sex == "1", year != 2018) %>% arrange(rev(year)),
           stat = "identity",
           position = "identity",
           mapping = aes(y = -pop)) +
  #steps for 2018 census
  geom_step(data =  df2 %>% filter(sex == "2", year == 2018), 
            aes(x = ageno)) +
  geom_step(data =  df2 %>% filter(sex == "1", year == 2018), 
            aes(x = ageno, y = -pop)) +
  coord_flip() +
  scale_y_continuous(labels = abs) +
  scale_fill_viridis_c(option = "cividis") # Add this line to use cividis color palette


# danereconstruction<-ggplot(data = df2, aes(x = age, y = pop, fill = year)) +
#   #bars for all but 2018
#   geom_bar(data = df2 %>% filter(sex == "2", year != 2018) %>% arrange(rev(year)),
#            stat = "identity",
#            position = "identity") +
#   geom_bar(data = df2 %>% filter(sex == "1", year != 2018) %>% arrange(rev(year)),
#            stat = "identity",
#            position = "identity",
#            mapping = aes(y = -pop)) +
#   #steps for 2018 census
#   geom_step(data =  df2 %>% filter(sex == "2", year == 2018), 
#             aes(x = ageno)) +
#   geom_step(data =  df2 %>% filter(sex == "1", year == 2018), 
#             aes(x = ageno, y = -pop)) +
#   coord_flip() +
#   scale_y_continuous(labels = abs)

#Save graph
ggsave("Output/danereconstruction.png")


